whisk:
  ingress:
    type: NodePort
    apiHostName: 172.21.0.3
    apiHostPort: 31001
  limits:
    actionsInvokesPerminute: 999
    actionsInvokesConcurrent: 999
    triggersFiresPerminute: 60
    actionsSequenceMaxlength: 50
    actions:
      time:
        min: "100ms"
        max: "5m"
        std: "1m"
      memory:
        min: "512m"
        max: "2048m"
        std: "512m"
      concurrency:
        min: 1
        max: 1
        std: 1
      log:
        min: "0m"
        max: "5m"
        std: "5m"
    activation:
      payload:
        max: "1048576"
  containerPool:
    userMemory: "8192m"
invoker:
  containerFactory:
    impl: kubernetes
nginx:
  httpsNodePort: '31001'
apiHostPort : 31001,


#memory:
#  min
#  /
#containerPool:
#  userMemory
#  =
#  containerCount
#
