whisk:
  ingress:
    type: NodePort
    apiHostName: 192.168.1.27
    apiHostPort: 31001
    limits:
      actionsInvokesPerminute: 999
      actionsInvokesConcurrent: 999
      actions:
        log:
          max: "5m"
          std: "5m"
invoker:
  containerFactory:
    impl: kubernetes
nginx:
  httpsNodePort: '31001'
apiHostPort : 31001,
