---
- hosts: localhost
  vars_files:
    - required-files/cluster-info.yaml
  tasks:
    - name: node label master
      k8s:
        kubeconfig: '{{ kubeconfig }}'
        definition:
          apiversion: v1
          kind: Node
          metadata:
            name: '{{ masterNode }}'
            labels: 
              openwhisk-role: core
    - name: node label worker1
      k8s:
        kubeconfig: '{{ kubeconfig }}'
        definition:
          apiversion: v1
          kind: Node
          metadata:
            name: '{{ workerNode1 }}'
            labels: 
              openwhisk-role: invoker
    - name: node label worker2
      k8s:
        kubeconfig: '{{ kubeconfig }}'
        definition:
          apiversion: v1
          kind: Node
          metadata:
            name: '{{ workerNode2 }}'
            labels: 
              openwhisk-role: invoker
