---
- hosts: localhost
  vars:
    kubeconfig: ./required-files/vagrant-cluster.yaml
  tasks:
    - name: node label
      k8s:
        kubeconfig: './required-files/vagrant-cluster.yaml'
        definition:
          apiversion: v1
          kind: Node
          metadata:
            name: master
            labels: 
              openwhisk-role: core
    - name: node label2
      k8s:
        kubeconfig: './required-files/vagrant-cluster.yaml'
        definition:
          kubeconfig: './required-files/vagrant-cluster.yaml'
          apiversion: v1
          kind: Node
          metadata:
            name: node-01
            labels: 
              openwhisk-role: invoker
    - name: get apiHostName 
      shell: "kubectl describe node master | grep InternalIP: | awk '{print $2}'"
      register: apiHostName
    - name: setup mycluster.yaml
      lineinfile:
        dest: "required-files/mycluster.yaml"
        regex: "^apiHostName :"
        line: "apiHostName : {{ apiHostName}},"
        state: present
      lineinfile:
        dest: "required-files/mycluster.yaml"
        regex: "^apiHostPort :"
        line: "apiHostPort : 31001,"
        state: present
        
        
