---
- hosts: localhost
  vars:
    minMemory: "512m"
    maxMemory: "2048m"
    userMemory: "1024m"
  vars_files:
    - required-files/cluster-info.yaml
  tasks:
    - name: get apiHostName
      shell: "kubectl describe node {{ masterNode }} | grep InternalIP | awk '{print $2}'"
      register: apiHostName
    - name: edit values
      template:
        src: required-files/mycluster.yaml.j2
        dest: required-files/mycluster.yaml
